language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
before_install:
  - pip install --upgrade pip
  - pip install --upgrade pip setuptools
install:
  - pip install --install-option="--no-cython-compile" Cython
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev gfortran

  # Some issue for scikit-learn dependencies
  - pip install --no-deps scikit-learn --cache-dir $HOME/.pip-cache
  - pip install --no-deps matplotlib>=1.4.0 --cache-dir $HOME/.pip-cache
  - pip install --no-deps scipy>=0.14.0 --cache-dir $HOME/.pip-cache

  - sudo apt-get install python-numpy python-scipy

  - pip install -r requirements/travis.txt --cache-dir $HOME/.pip-cache
script:
  - nosetests -v tests
  - flake8 neuralpy/ --exclude=neuralpy/commands/new_project_template/,__init__.py
addons:
  apt:
    packages:
      - libatlas3gf-base
      - libatlas-dev
      - python-scipy
cache:
  directories:
    - $HOME/.pip-cache/
