language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
before_install:
  - pip install --upgrade pip
  - pip install --upgrade pip setuptools

  - pip install --install-option="--no-cython-compile" Cython
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev gfortran
install:
  # Some issue for scikit-learn dependencies
  - pip install --no-deps scikit-learn
  - pip install -r requirements/test.txt
script: tox
addons:
  apt:
    packages:
      - libatlas3gf-base
      - libatlas-dev
      - python-scipy
